/* Generated by scripts/generate_imports.py. Do not silently stub APIs. */
#include <vitasdk.h>
#include "port.h"
#include "so_util.h"
extern void import_0(void) __asm__("_ZSt7nothrow");
extern void import_1(void) __asm__("_ZnajRKSt9nothrow_t");
extern void import_2(void) __asm__("__aeabi_atexit");
extern void import_3(void) __asm__("__aeabi_d2iz");
extern void import_4(void) __asm__("__aeabi_d2lz");
extern void import_5(void) __asm__("__aeabi_dadd");
extern void import_6(void) __asm__("__aeabi_dmul");
extern void import_7(void) __asm__("__aeabi_i2d");
extern void import_8(void) __asm__("__aeabi_idiv");
extern void import_9(void) __asm__("__aeabi_idivmod");
extern void import_10(void) __asm__("__aeabi_ldivmod");
extern void import_11(void) __asm__("__aeabi_uidiv");
extern void import_12(void) __asm__("__aeabi_uidivmod");
extern void import_13(void) __asm__("__aeabi_ul2d");
extern void import_14(void) __asm__("__aeabi_uldivmod");
extern void import_15(void) __asm__("__aeabi_unwind_cpp_pr0");
extern void import_16(void) __asm__("__aeabi_unwind_cpp_pr1");
extern void import_17(void) __asm__("sf_android_log_print");
extern void import_18(void) __asm__("sf_android_log_write");
extern void import_19(void) __asm__("__cxa_guard_acquire");
extern void import_20(void) __asm__("__cxa_guard_release");
extern void import_21(void) __asm__("__cxa_pure_virtual");
extern void import_22(void) __asm__("sf_dso_handle");
extern void import_23(void) __asm__("__errno");
extern void import_24(void) __asm__("sf_stdio");
extern void import_25(void) __asm__("sf_getc");
extern void import_26(void) __asm__("sf_stack_fail");
extern void import_27(void) __asm__("sf_stack_guard");
extern void import_28(void) __asm__("sf_ctype");
extern void import_29(void) __asm__("sf_lower");
extern void import_30(void) __asm__("sf_upper");
extern void import_31(void) __asm__("sf_abort");
static void import_32(void) { fatal_error("Unimplemented import: accept"); }
extern void import_33(void) __asm__("acos");
extern void import_34(void) __asm__("acosf");
extern void import_35(void) __asm__("asinf");
extern void import_36(void) __asm__("atan");
extern void import_37(void) __asm__("atan2");
extern void import_38(void) __asm__("atan2f");
extern void import_39(void) __asm__("atanf");
extern void import_40(void) __asm__("atoi");
static void import_41(void) { fatal_error("Unimplemented import: bind"); }
extern void import_42(void) __asm__("calloc");
extern void import_43(void) __asm__("ceil");
extern void import_44(void) __asm__("ceilf");
extern void import_45(void) __asm__("sf_chdir");
extern void import_46(void) __asm__("clock");
extern void import_47(void) __asm__("sf_close");
static void import_48(void) { fatal_error("Unimplemented import: connect"); }
extern void import_49(void) __asm__("cos");
extern void import_50(void) __asm__("cosf");
extern void import_51(void) __asm__("cosh");
extern void import_52(void) __asm__("difftime");
extern void import_53(void) __asm__("sf_exit");
extern void import_54(void) __asm__("expf");
extern void import_55(void) __asm__("sf_fclose");
extern void import_56(void) __asm__("sf_fcntl");
extern void import_57(void) __asm__("sf_fflush");
extern void import_58(void) __asm__("sf_fgetpos");
extern void import_59(void) __asm__("sf_fgets");
extern void import_60(void) __asm__("floor");
extern void import_61(void) __asm__("floorf");
extern void import_62(void) __asm__("fmodf");
extern void import_63(void) __asm__("sf_fopen");
extern void import_64(void) __asm__("sf_fprintf");
extern void import_65(void) __asm__("sf_putc");
extern void import_66(void) __asm__("sf_fputs");
extern void import_67(void) __asm__("sf_fread");
extern void import_68(void) __asm__("free");
static void import_69(void) { fatal_error("Unimplemented import: freeaddrinfo"); }
extern void import_70(void) __asm__("sf_freopen");
extern void import_71(void) __asm__("frexpf");
extern void import_72(void) __asm__("sf_fscanf");
extern void import_73(void) __asm__("sf_fseek");
extern void import_74(void) __asm__("sf_fsetpos");
extern void import_75(void) __asm__("sf_fstat");
extern void import_76(void) __asm__("sf_ftell");
extern void import_77(void) __asm__("sf_fwrite");
static void import_78(void) { fatal_error("Unimplemented import: getaddrinfo"); }
extern void import_79(void) __asm__("sf_getc");
extern void import_80(void) __asm__("sf_getenv");
extern void import_81(void) __asm__("sf_gethostbyname");
extern void import_82(void) __asm__("sf_gethostname");
static void import_83(void) { fatal_error("Unimplemented import: getsockname"); }
static void import_84(void) { fatal_error("Unimplemented import: getsockopt"); }
extern void import_85(void) __asm__("gettimeofday");
#ifdef STARFRONT_GL_TRACE
extern void import_86(void) __asm__("sf_trace_glActiveTexture");
#else
extern void import_86(void) __asm__("glActiveTexture");
#endif
extern void import_87(void) __asm__("glAlphaFunc");
extern void import_88(void) __asm__("glAttachShader");
extern void import_89(void) __asm__("glBindAttribLocation");
#ifdef STARFRONT_GL_TRACE
extern void import_90(void) __asm__("sf_trace_glBindBuffer");
#else
extern void import_90(void) __asm__("glBindBuffer");
#endif
#ifdef STARFRONT_GL_TRACE
extern void import_91(void) __asm__("sf_trace_glBindFramebuffer");
#else
extern void import_91(void) __asm__("sf_glBindFramebuffer");
#endif
#ifdef STARFRONT_GL_TRACE
extern void import_92(void) __asm__("sf_trace_glBindFramebuffer");
#else
extern void import_92(void) __asm__("sf_glBindFramebuffer");
#endif
extern void import_93(void) __asm__("glBindRenderbuffer");
extern void import_94(void) __asm__("glBindRenderbuffer");
#ifdef STARFRONT_GL_TRACE
extern void import_95(void) __asm__("sf_trace_glBindTexture");
#else
extern void import_95(void) __asm__("glBindTexture");
#endif
extern void import_96(void) __asm__("sf_glBlendColor");
extern void import_97(void) __asm__("glBlendEquation");
extern void import_98(void) __asm__("glBlendEquation");
extern void import_99(void) __asm__("sf_glBlendFunc");
extern void import_100(void) __asm__("glBufferData");
extern void import_101(void) __asm__("glBufferSubData");
extern void import_102(void) __asm__("glCheckFramebufferStatus");
extern void import_103(void) __asm__("glCheckFramebufferStatus");
#ifdef STARFRONT_GL_TRACE
extern void import_104(void) __asm__("sf_trace_glClear");
#else
extern void import_104(void) __asm__("glClear");
#endif
#ifdef STARFRONT_GL_TRACE
extern void import_105(void) __asm__("sf_trace_glClearColor");
#else
extern void import_105(void) __asm__("glClearColor");
#endif
extern void import_106(void) __asm__("glClearDepthf");
extern void import_107(void) __asm__("glClearStencil");
extern void import_108(void) __asm__("glClientActiveTexture");
extern void import_109(void) __asm__("glClipPlanef");
extern void import_110(void) __asm__("glColor4f");
extern void import_111(void) __asm__("glColor4ub");
#ifdef STARFRONT_GL_TRACE
extern void import_112(void) __asm__("sf_trace_glColorMask");
#else
extern void import_112(void) __asm__("glColorMask");
#endif
extern void import_113(void) __asm__("glColorPointer");
extern void import_114(void) __asm__("sf_glCompileShader");
#ifdef STARFRONT_GL_TRACE
extern void import_115(void) __asm__("sf_trace_glCompressedTexImage2D");
#else
extern void import_115(void) __asm__("glCompressedTexImage2D");
#endif
static void import_116(void) { fatal_error("Unimplemented import: glCompressedTexImage3DOES"); }
static void import_117(void) { fatal_error("Unimplemented import: glCompressedTexSubImage2D"); }
static void import_118(void) { fatal_error("Unimplemented import: glCompressedTexSubImage3DOES"); }
extern void import_119(void) __asm__("glCopyTexImage2D");
extern void import_120(void) __asm__("glCopyTexSubImage2D");
extern void import_121(void) __asm__("glCreateProgram");
extern void import_122(void) __asm__("glCreateShader");
#ifdef STARFRONT_GL_TRACE
extern void import_123(void) __asm__("sf_trace_glCullFace");
#else
extern void import_123(void) __asm__("glCullFace");
#endif
extern void import_124(void) __asm__("glDeleteBuffers");
extern void import_125(void) __asm__("glDeleteFramebuffers");
extern void import_126(void) __asm__("glDeleteFramebuffers");
extern void import_127(void) __asm__("glDeleteProgram");
extern void import_128(void) __asm__("glDeleteRenderbuffers");
extern void import_129(void) __asm__("glDeleteRenderbuffers");
extern void import_130(void) __asm__("glDeleteShader");
extern void import_131(void) __asm__("glDeleteTextures");
extern void import_132(void) __asm__("glDepthFunc");
extern void import_133(void) __asm__("glDepthMask");
extern void import_134(void) __asm__("glDepthRangef");
#ifdef STARFRONT_GL_TRACE
extern void import_135(void) __asm__("sf_trace_glDisable");
#else
extern void import_135(void) __asm__("glDisable");
#endif
extern void import_136(void) __asm__("glDisableClientState");
#ifdef STARFRONT_GL_TRACE
extern void import_137(void) __asm__("sf_trace_glDisableVertexAttribArray");
#else
extern void import_137(void) __asm__("glDisableVertexAttribArray");
#endif
#ifdef STARFRONT_GL_TRACE
extern void import_138(void) __asm__("sf_trace_glDrawArrays");
#else
extern void import_138(void) __asm__("glDrawArrays");
#endif
#ifdef STARFRONT_GL_TRACE
extern void import_139(void) __asm__("sf_trace_glDrawElements");
#else
extern void import_139(void) __asm__("glDrawElements");
#endif
#ifdef STARFRONT_GL_TRACE
extern void import_140(void) __asm__("sf_trace_glEnable");
#else
extern void import_140(void) __asm__("glEnable");
#endif
extern void import_141(void) __asm__("glEnableClientState");
#ifdef STARFRONT_GL_TRACE
extern void import_142(void) __asm__("sf_trace_glEnableVertexAttribArray");
#else
extern void import_142(void) __asm__("glEnableVertexAttribArray");
#endif
extern void import_143(void) __asm__("glFlush");
extern void import_144(void) __asm__("glFogf");
extern void import_145(void) __asm__("glFogfv");
extern void import_146(void) __asm__("glFramebufferRenderbuffer");
extern void import_147(void) __asm__("glFramebufferRenderbuffer");
extern void import_148(void) __asm__("glFramebufferTexture2D");
extern void import_149(void) __asm__("glFramebufferTexture2D");
#ifdef STARFRONT_GL_TRACE
extern void import_150(void) __asm__("sf_trace_glFrontFace");
#else
extern void import_150(void) __asm__("glFrontFace");
#endif
extern void import_151(void) __asm__("glGenBuffers");
extern void import_152(void) __asm__("glGenFramebuffers");
extern void import_153(void) __asm__("glGenFramebuffers");
extern void import_154(void) __asm__("glGenRenderbuffers");
extern void import_155(void) __asm__("glGenRenderbuffers");
extern void import_156(void) __asm__("glGenTextures");
extern void import_157(void) __asm__("glGenerateMipmap");
extern void import_158(void) __asm__("glGenerateMipmap");
extern void import_159(void) __asm__("glGetActiveAttrib");
extern void import_160(void) __asm__("glGetActiveUniform");
#ifdef STARFRONT_GL_TRACE
extern void import_161(void) __asm__("sf_trace_glGetAttribLocation");
#else
extern void import_161(void) __asm__("glGetAttribLocation");
#endif
#ifdef STARFRONT_GL_TRACE
extern void import_162(void) __asm__("sf_trace_glGetError");
#else
extern void import_162(void) __asm__("glGetError");
#endif
extern void import_163(void) __asm__("sf_glGetFloatv");
extern void import_164(void) __asm__("sf_glGetIntegerv");
extern void import_165(void) __asm__("glGetProgramInfoLog");
extern void import_166(void) __asm__("glGetProgramiv");
extern void import_167(void) __asm__("glGetShaderInfoLog");
extern void import_168(void) __asm__("glGetShaderiv");
extern void import_169(void) __asm__("glGetString");
#ifdef STARFRONT_GL_TRACE
extern void import_170(void) __asm__("sf_trace_glGetUniformLocation");
#else
extern void import_170(void) __asm__("glGetUniformLocation");
#endif
extern void import_171(void) __asm__("glHint");
static void import_172(void) { fatal_error("Unimplemented import: glLightModelf"); }
extern void import_173(void) __asm__("glLightModelfv");
extern void import_174(void) __asm__("sf_glLightf");
extern void import_175(void) __asm__("glLightfv");
extern void import_176(void) __asm__("glLineWidth");
extern void import_177(void) __asm__("sf_glLinkProgram");
extern void import_178(void) __asm__("glLoadIdentity");
extern void import_179(void) __asm__("glLoadMatrixf");
extern void import_180(void) __asm__("glMapBuffer");
extern void import_181(void) __asm__("sf_glMaterialf");
extern void import_182(void) __asm__("glMaterialfv");
extern void import_183(void) __asm__("glMatrixMode");
extern void import_184(void) __asm__("glMultMatrixf");
static void import_185(void) { fatal_error("Unimplemented import: glMultiTexCoord4f"); }
extern void import_186(void) __asm__("glNormal3f");
extern void import_187(void) __asm__("glNormalPointer");
#ifdef STARFRONT_GL_TRACE
extern void import_188(void) __asm__("sf_trace_glPixelStorei");
#else
extern void import_188(void) __asm__("glPixelStorei");
#endif
static void import_189(void) { fatal_error("Unimplemented import: glPointParameterf"); }
static void import_190(void) { fatal_error("Unimplemented import: glPointParameterfv"); }
extern void import_191(void) __asm__("glPointSize");
extern void import_192(void) __asm__("glPolygonOffset");
extern void import_193(void) __asm__("glPopMatrix");
extern void import_194(void) __asm__("glPushMatrix");
extern void import_195(void) __asm__("glReadPixels");
extern void import_196(void) __asm__("glRenderbufferStorage");
extern void import_197(void) __asm__("glRenderbufferStorage");
extern void import_198(void) __asm__("sf_glSampleCoverage");
#ifdef STARFRONT_GL_TRACE
extern void import_199(void) __asm__("sf_trace_glScissor");
#else
extern void import_199(void) __asm__("sf_glScissor");
#endif
extern void import_200(void) __asm__("glShadeModel");
extern void import_201(void) __asm__("glShaderSource");
extern void import_202(void) __asm__("glStencilMask");
extern void import_203(void) __asm__("glTexCoordPointer");
extern void import_204(void) __asm__("glTexEnvf");
extern void import_205(void) __asm__("glTexEnvfv");
extern void import_206(void) __asm__("glTexEnvi");
#ifdef STARFRONT_GL_TRACE
extern void import_207(void) __asm__("sf_trace_glTexImage2D");
#else
extern void import_207(void) __asm__("glTexImage2D");
#endif
static void import_208(void) { fatal_error("Unimplemented import: glTexImage3DOES"); }
extern void import_209(void) __asm__("glTexParameterf");
extern void import_210(void) __asm__("glTexParameteri");
extern void import_211(void) __asm__("glTexSubImage2D");
static void import_212(void) { fatal_error("Unimplemented import: glTexSubImage3DOES"); }
extern void import_213(void) __asm__("glUniform1f");
extern void import_214(void) __asm__("glUniform1fv");
#ifdef STARFRONT_GL_TRACE
extern void import_215(void) __asm__("sf_trace_glUniform1i");
#else
extern void import_215(void) __asm__("glUniform1i");
#endif
#ifdef STARFRONT_GL_TRACE
extern void import_216(void) __asm__("sf_trace_glUniform1iv");
#else
extern void import_216(void) __asm__("glUniform1iv");
#endif
extern void import_217(void) __asm__("glUniform2fv");
extern void import_218(void) __asm__("glUniform2iv");
extern void import_219(void) __asm__("glUniform3fv");
extern void import_220(void) __asm__("glUniform3iv");
extern void import_221(void) __asm__("glUniform4fv");
extern void import_222(void) __asm__("glUniform4iv");
#ifdef STARFRONT_GL_TRACE
extern void import_223(void) __asm__("sf_trace_glUniformMatrix4fv");
#else
extern void import_223(void) __asm__("glUniformMatrix4fv");
#endif
extern void import_224(void) __asm__("glUnmapBuffer");
#ifdef STARFRONT_GL_TRACE
extern void import_225(void) __asm__("sf_trace_glUseProgram");
#else
extern void import_225(void) __asm__("glUseProgram");
#endif
extern void import_226(void) __asm__("glVertexAttrib4f");
#ifdef STARFRONT_GL_TRACE
extern void import_227(void) __asm__("sf_trace_glVertexAttribPointer");
#else
extern void import_227(void) __asm__("glVertexAttribPointer");
#endif
extern void import_228(void) __asm__("glVertexPointer");
#ifdef STARFRONT_GL_TRACE
extern void import_229(void) __asm__("sf_trace_glViewport");
#else
extern void import_229(void) __asm__("sf_glViewport");
#endif
extern void import_230(void) __asm__("gmtime");
extern void import_231(void) __asm__("inet_addr");
extern void import_232(void) __asm__("inet_ntoa");
static void import_233(void) { fatal_error("Unimplemented import: ioctl"); }
extern void import_234(void) __asm__("iswalpha");
extern void import_235(void) __asm__("iswcntrl");
extern void import_236(void) __asm__("iswdigit");
extern void import_237(void) __asm__("iswlower");
extern void import_238(void) __asm__("iswprint");
extern void import_239(void) __asm__("iswpunct");
extern void import_240(void) __asm__("iswspace");
extern void import_241(void) __asm__("iswupper");
extern void import_242(void) __asm__("iswxdigit");
extern void import_243(void) __asm__("ldexpf");
static void import_244(void) { fatal_error("Unimplemented import: listen"); }
extern void import_245(void) __asm__("localtime");
extern void import_246(void) __asm__("localtime_r");
extern void import_247(void) __asm__("log10");
extern void import_248(void) __asm__("logf");
extern void import_249(void) __asm__("longjmp");
extern void import_250(void) __asm__("lrand48");
extern void import_251(void) __asm__("lseek");
extern void import_252(void) __asm__("malloc");
extern void import_253(void) __asm__("memchr");
extern void import_254(void) __asm__("memcmp");
extern void import_255(void) __asm__("memcpy");
extern void import_256(void) __asm__("memmove");
extern void import_257(void) __asm__("memset");
extern void import_258(void) __asm__("mktime");
static void import_259(void) { fatal_error("Unimplemented import: mmap"); }
extern void import_260(void) __asm__("modff");
static void import_261(void) { fatal_error("Unimplemented import: munmap"); }
extern void import_262(void) __asm__("nanosleep");
extern void import_263(void) __asm__("sf_open");
extern void import_264(void) __asm__("pow");
extern void import_265(void) __asm__("powf");
extern void import_266(void) __asm__("sf_printf");
extern void import_267(void) __asm__("sf_pthread_create");
extern void import_268(void) __asm__("pthread_exit");
extern void import_269(void) __asm__("pthread_getspecific");
extern void import_270(void) __asm__("pthread_join");
extern void import_271(void) __asm__("pthread_key_create");
static void import_272(void) { fatal_error("Unimplemented import: pthread_kill"); }
extern void import_273(void) __asm__("sf_mutex_destroy");
extern void import_274(void) __asm__("sf_mutex_init");
extern void import_275(void) __asm__("sf_mutex_lock");
extern void import_276(void) __asm__("sf_mutex_trylock");
extern void import_277(void) __asm__("sf_mutex_unlock");
extern void import_278(void) __asm__("pthread_self");
extern void import_279(void) __asm__("pthread_setspecific");
extern void import_280(void) __asm__("sf_putc");
extern void import_281(void) __asm__("putchar");
extern void import_282(void) __asm__("sf_puts");
extern void import_283(void) __asm__("qsort");
extern void import_284(void) __asm__("read");
extern void import_285(void) __asm__("realloc");
static void import_286(void) { fatal_error("Unimplemented import: recv"); }
static void import_287(void) { fatal_error("Unimplemented import: recvfrom"); }
extern void import_288(void) __asm__("sf_remove");
extern void import_289(void) __asm__("sf_rename");
static void import_290(void) { fatal_error("Unimplemented import: select"); }
static void import_291(void) { fatal_error("Unimplemented import: send"); }
static void import_292(void) { fatal_error("Unimplemented import: sendto"); }
extern void import_293(void) __asm__("setjmp");
extern void import_294(void) __asm__("setlocale");
static void import_295(void) { fatal_error("Unimplemented import: setsockopt"); }
extern void import_296(void) __asm__("sf_setvbuf");
extern void import_297(void) __asm__("sf_sigaction");
extern void import_298(void) __asm__("sin");
extern void import_299(void) __asm__("sinf");
extern void import_300(void) __asm__("sinh");
extern void import_301(void) __asm__("snprintf");
extern void import_302(void) __asm__("sf_socket");
extern void import_303(void) __asm__("sprintf");
extern void import_304(void) __asm__("sqrt");
extern void import_305(void) __asm__("sqrtf");
extern void import_306(void) __asm__("srand48");
extern void import_307(void) __asm__("sscanf");
extern void import_308(void) __asm__("strcasecmp");
extern void import_309(void) __asm__("strcat");
extern void import_310(void) __asm__("strchr");
extern void import_311(void) __asm__("strcmp");
extern void import_312(void) __asm__("strcoll");
extern void import_313(void) __asm__("strcpy");
extern void import_314(void) __asm__("strcspn");
extern void import_315(void) __asm__("strerror");
extern void import_316(void) __asm__("strftime");
extern void import_317(void) __asm__("strlcpy");
extern void import_318(void) __asm__("strlen");
extern void import_319(void) __asm__("strncasecmp");
extern void import_320(void) __asm__("strncat");
extern void import_321(void) __asm__("strncmp");
extern void import_322(void) __asm__("strncpy");
extern void import_323(void) __asm__("strpbrk");
extern void import_324(void) __asm__("strrchr");
extern void import_325(void) __asm__("strstr");
extern void import_326(void) __asm__("strtod");
extern void import_327(void) __asm__("strtok");
extern void import_328(void) __asm__("strtol");
extern void import_329(void) __asm__("strtoul");
extern void import_330(void) __asm__("swprintf");
extern void import_331(void) __asm__("sf_sysconf");
static void import_332(void) { fatal_error("Unimplemented import: system"); }
extern void import_333(void) __asm__("tan");
extern void import_334(void) __asm__("tanf");
extern void import_335(void) __asm__("tanh");
extern void import_336(void) __asm__("time");
extern void import_337(void) __asm__("sf_tmpfile");
static void import_338(void) { fatal_error("Unimplemented import: tmpnam"); }
extern void import_339(void) __asm__("towlower");
extern void import_340(void) __asm__("towupper");
extern void import_341(void) __asm__("sf_ungetc");
extern void import_342(void) __asm__("sf_remove");
extern void import_343(void) __asm__("usleep");
extern void import_344(void) __asm__("vsnprintf");
extern void import_345(void) __asm__("vsprintf");
extern void import_346(void) __asm__("wcscmp");
extern void import_347(void) __asm__("wcscpy");
extern void import_348(void) __asm__("wcslen");
extern void import_349(void) __asm__("wcsncpy");
extern void import_350(void) __asm__("write");
so_default_dynlib port_imports[] = {
    {"_ZSt7nothrow", (uintptr_t)&import_0},
    {"_ZnajRKSt9nothrow_t", (uintptr_t)&import_1},
    {"__aeabi_atexit", (uintptr_t)&import_2},
    {"__aeabi_d2iz", (uintptr_t)&import_3},
    {"__aeabi_d2lz", (uintptr_t)&import_4},
    {"__aeabi_dadd", (uintptr_t)&import_5},
    {"__aeabi_dmul", (uintptr_t)&import_6},
    {"__aeabi_i2d", (uintptr_t)&import_7},
    {"__aeabi_idiv", (uintptr_t)&import_8},
    {"__aeabi_idivmod", (uintptr_t)&import_9},
    {"__aeabi_ldivmod", (uintptr_t)&import_10},
    {"__aeabi_uidiv", (uintptr_t)&import_11},
    {"__aeabi_uidivmod", (uintptr_t)&import_12},
    {"__aeabi_ul2d", (uintptr_t)&import_13},
    {"__aeabi_uldivmod", (uintptr_t)&import_14},
    {"__aeabi_unwind_cpp_pr0", (uintptr_t)&import_15},
    {"__aeabi_unwind_cpp_pr1", (uintptr_t)&import_16},
    {"__android_log_print", (uintptr_t)&import_17},
    {"__android_log_write", (uintptr_t)&import_18},
    {"__cxa_guard_acquire", (uintptr_t)&import_19},
    {"__cxa_guard_release", (uintptr_t)&import_20},
    {"__cxa_pure_virtual", (uintptr_t)&import_21},
    {"__dso_handle", (uintptr_t)&import_22},
    {"__errno", (uintptr_t)&import_23},
    {"__sF", (uintptr_t)&import_24},
    {"__srget", (uintptr_t)&import_25},
    {"__stack_chk_fail", (uintptr_t)&import_26},
    {"__stack_chk_guard", (uintptr_t)&import_27},
    {"_ctype_", (uintptr_t)&import_28},
    {"_tolower_tab_", (uintptr_t)&import_29},
    {"_toupper_tab_", (uintptr_t)&import_30},
    {"abort", (uintptr_t)&import_31},
    {"accept", (uintptr_t)&import_32},
    {"acos", (uintptr_t)&import_33},
    {"acosf", (uintptr_t)&import_34},
    {"asinf", (uintptr_t)&import_35},
    {"atan", (uintptr_t)&import_36},
    {"atan2", (uintptr_t)&import_37},
    {"atan2f", (uintptr_t)&import_38},
    {"atanf", (uintptr_t)&import_39},
    {"atoi", (uintptr_t)&import_40},
    {"bind", (uintptr_t)&import_41},
    {"calloc", (uintptr_t)&import_42},
    {"ceil", (uintptr_t)&import_43},
    {"ceilf", (uintptr_t)&import_44},
    {"chdir", (uintptr_t)&import_45},
    {"clock", (uintptr_t)&import_46},
    {"close", (uintptr_t)&import_47},
    {"connect", (uintptr_t)&import_48},
    {"cos", (uintptr_t)&import_49},
    {"cosf", (uintptr_t)&import_50},
    {"cosh", (uintptr_t)&import_51},
    {"difftime", (uintptr_t)&import_52},
    {"exit", (uintptr_t)&import_53},
    {"expf", (uintptr_t)&import_54},
    {"fclose", (uintptr_t)&import_55},
    {"fcntl", (uintptr_t)&import_56},
    {"fflush", (uintptr_t)&import_57},
    {"fgetpos", (uintptr_t)&import_58},
    {"fgets", (uintptr_t)&import_59},
    {"floor", (uintptr_t)&import_60},
    {"floorf", (uintptr_t)&import_61},
    {"fmodf", (uintptr_t)&import_62},
    {"fopen", (uintptr_t)&import_63},
    {"fprintf", (uintptr_t)&import_64},
    {"fputc", (uintptr_t)&import_65},
    {"fputs", (uintptr_t)&import_66},
    {"fread", (uintptr_t)&import_67},
    {"free", (uintptr_t)&import_68},
    {"freeaddrinfo", (uintptr_t)&import_69},
    {"freopen", (uintptr_t)&import_70},
    {"frexpf", (uintptr_t)&import_71},
    {"fscanf", (uintptr_t)&import_72},
    {"fseek", (uintptr_t)&import_73},
    {"fsetpos", (uintptr_t)&import_74},
    {"fstat", (uintptr_t)&import_75},
    {"ftell", (uintptr_t)&import_76},
    {"fwrite", (uintptr_t)&import_77},
    {"getaddrinfo", (uintptr_t)&import_78},
    {"getc", (uintptr_t)&import_79},
    {"getenv", (uintptr_t)&import_80},
    {"gethostbyname", (uintptr_t)&import_81},
    {"gethostname", (uintptr_t)&import_82},
    {"getsockname", (uintptr_t)&import_83},
    {"getsockopt", (uintptr_t)&import_84},
    {"gettimeofday", (uintptr_t)&import_85},
    {"glActiveTexture", (uintptr_t)&import_86},
    {"glAlphaFunc", (uintptr_t)&import_87},
    {"glAttachShader", (uintptr_t)&import_88},
    {"glBindAttribLocation", (uintptr_t)&import_89},
    {"glBindBuffer", (uintptr_t)&import_90},
    {"glBindFramebuffer", (uintptr_t)&import_91},
    {"glBindFramebufferOES", (uintptr_t)&import_92},
    {"glBindRenderbuffer", (uintptr_t)&import_93},
    {"glBindRenderbufferOES", (uintptr_t)&import_94},
    {"glBindTexture", (uintptr_t)&import_95},
    {"glBlendColor", (uintptr_t)&import_96},
    {"glBlendEquation", (uintptr_t)&import_97},
    {"glBlendEquationOES", (uintptr_t)&import_98},
    {"glBlendFunc", (uintptr_t)&import_99},
    {"glBufferData", (uintptr_t)&import_100},
    {"glBufferSubData", (uintptr_t)&import_101},
    {"glCheckFramebufferStatus", (uintptr_t)&import_102},
    {"glCheckFramebufferStatusOES", (uintptr_t)&import_103},
    {"glClear", (uintptr_t)&import_104},
    {"glClearColor", (uintptr_t)&import_105},
    {"glClearDepthf", (uintptr_t)&import_106},
    {"glClearStencil", (uintptr_t)&import_107},
    {"glClientActiveTexture", (uintptr_t)&import_108},
    {"glClipPlanef", (uintptr_t)&import_109},
    {"glColor4f", (uintptr_t)&import_110},
    {"glColor4ub", (uintptr_t)&import_111},
    {"glColorMask", (uintptr_t)&import_112},
    {"glColorPointer", (uintptr_t)&import_113},
    {"glCompileShader", (uintptr_t)&import_114},
    {"glCompressedTexImage2D", (uintptr_t)&import_115},
    {"glCompressedTexImage3DOES", (uintptr_t)&import_116},
    {"glCompressedTexSubImage2D", (uintptr_t)&import_117},
    {"glCompressedTexSubImage3DOES", (uintptr_t)&import_118},
    {"glCopyTexImage2D", (uintptr_t)&import_119},
    {"glCopyTexSubImage2D", (uintptr_t)&import_120},
    {"glCreateProgram", (uintptr_t)&import_121},
    {"glCreateShader", (uintptr_t)&import_122},
    {"glCullFace", (uintptr_t)&import_123},
    {"glDeleteBuffers", (uintptr_t)&import_124},
    {"glDeleteFramebuffers", (uintptr_t)&import_125},
    {"glDeleteFramebuffersOES", (uintptr_t)&import_126},
    {"glDeleteProgram", (uintptr_t)&import_127},
    {"glDeleteRenderbuffers", (uintptr_t)&import_128},
    {"glDeleteRenderbuffersOES", (uintptr_t)&import_129},
    {"glDeleteShader", (uintptr_t)&import_130},
    {"glDeleteTextures", (uintptr_t)&import_131},
    {"glDepthFunc", (uintptr_t)&import_132},
    {"glDepthMask", (uintptr_t)&import_133},
    {"glDepthRangef", (uintptr_t)&import_134},
    {"glDisable", (uintptr_t)&import_135},
    {"glDisableClientState", (uintptr_t)&import_136},
    {"glDisableVertexAttribArray", (uintptr_t)&import_137},
    {"glDrawArrays", (uintptr_t)&import_138},
    {"glDrawElements", (uintptr_t)&import_139},
    {"glEnable", (uintptr_t)&import_140},
    {"glEnableClientState", (uintptr_t)&import_141},
    {"glEnableVertexAttribArray", (uintptr_t)&import_142},
    {"glFlush", (uintptr_t)&import_143},
    {"glFogf", (uintptr_t)&import_144},
    {"glFogfv", (uintptr_t)&import_145},
    {"glFramebufferRenderbuffer", (uintptr_t)&import_146},
    {"glFramebufferRenderbufferOES", (uintptr_t)&import_147},
    {"glFramebufferTexture2D", (uintptr_t)&import_148},
    {"glFramebufferTexture2DOES", (uintptr_t)&import_149},
    {"glFrontFace", (uintptr_t)&import_150},
    {"glGenBuffers", (uintptr_t)&import_151},
    {"glGenFramebuffers", (uintptr_t)&import_152},
    {"glGenFramebuffersOES", (uintptr_t)&import_153},
    {"glGenRenderbuffers", (uintptr_t)&import_154},
    {"glGenRenderbuffersOES", (uintptr_t)&import_155},
    {"glGenTextures", (uintptr_t)&import_156},
    {"glGenerateMipmap", (uintptr_t)&import_157},
    {"glGenerateMipmapOES", (uintptr_t)&import_158},
    {"glGetActiveAttrib", (uintptr_t)&import_159},
    {"glGetActiveUniform", (uintptr_t)&import_160},
    {"glGetAttribLocation", (uintptr_t)&import_161},
    {"glGetError", (uintptr_t)&import_162},
    {"glGetFloatv", (uintptr_t)&import_163},
    {"glGetIntegerv", (uintptr_t)&import_164},
    {"glGetProgramInfoLog", (uintptr_t)&import_165},
    {"glGetProgramiv", (uintptr_t)&import_166},
    {"glGetShaderInfoLog", (uintptr_t)&import_167},
    {"glGetShaderiv", (uintptr_t)&import_168},
    {"glGetString", (uintptr_t)&import_169},
    {"glGetUniformLocation", (uintptr_t)&import_170},
    {"glHint", (uintptr_t)&import_171},
    {"glLightModelf", (uintptr_t)&import_172},
    {"glLightModelfv", (uintptr_t)&import_173},
    {"glLightf", (uintptr_t)&import_174},
    {"glLightfv", (uintptr_t)&import_175},
    {"glLineWidth", (uintptr_t)&import_176},
    {"glLinkProgram", (uintptr_t)&import_177},
    {"glLoadIdentity", (uintptr_t)&import_178},
    {"glLoadMatrixf", (uintptr_t)&import_179},
    {"glMapBufferOES", (uintptr_t)&import_180},
    {"glMaterialf", (uintptr_t)&import_181},
    {"glMaterialfv", (uintptr_t)&import_182},
    {"glMatrixMode", (uintptr_t)&import_183},
    {"glMultMatrixf", (uintptr_t)&import_184},
    {"glMultiTexCoord4f", (uintptr_t)&import_185},
    {"glNormal3f", (uintptr_t)&import_186},
    {"glNormalPointer", (uintptr_t)&import_187},
    {"glPixelStorei", (uintptr_t)&import_188},
    {"glPointParameterf", (uintptr_t)&import_189},
    {"glPointParameterfv", (uintptr_t)&import_190},
    {"glPointSize", (uintptr_t)&import_191},
    {"glPolygonOffset", (uintptr_t)&import_192},
    {"glPopMatrix", (uintptr_t)&import_193},
    {"glPushMatrix", (uintptr_t)&import_194},
    {"glReadPixels", (uintptr_t)&import_195},
    {"glRenderbufferStorage", (uintptr_t)&import_196},
    {"glRenderbufferStorageOES", (uintptr_t)&import_197},
    {"glSampleCoverage", (uintptr_t)&import_198},
    {"glScissor", (uintptr_t)&import_199},
    {"glShadeModel", (uintptr_t)&import_200},
    {"glShaderSource", (uintptr_t)&import_201},
    {"glStencilMask", (uintptr_t)&import_202},
    {"glTexCoordPointer", (uintptr_t)&import_203},
    {"glTexEnvf", (uintptr_t)&import_204},
    {"glTexEnvfv", (uintptr_t)&import_205},
    {"glTexEnvi", (uintptr_t)&import_206},
    {"glTexImage2D", (uintptr_t)&import_207},
    {"glTexImage3DOES", (uintptr_t)&import_208},
    {"glTexParameterf", (uintptr_t)&import_209},
    {"glTexParameteri", (uintptr_t)&import_210},
    {"glTexSubImage2D", (uintptr_t)&import_211},
    {"glTexSubImage3DOES", (uintptr_t)&import_212},
    {"glUniform1f", (uintptr_t)&import_213},
    {"glUniform1fv", (uintptr_t)&import_214},
    {"glUniform1i", (uintptr_t)&import_215},
    {"glUniform1iv", (uintptr_t)&import_216},
    {"glUniform2fv", (uintptr_t)&import_217},
    {"glUniform2iv", (uintptr_t)&import_218},
    {"glUniform3fv", (uintptr_t)&import_219},
    {"glUniform3iv", (uintptr_t)&import_220},
    {"glUniform4fv", (uintptr_t)&import_221},
    {"glUniform4iv", (uintptr_t)&import_222},
    {"glUniformMatrix4fv", (uintptr_t)&import_223},
    {"glUnmapBufferOES", (uintptr_t)&import_224},
    {"glUseProgram", (uintptr_t)&import_225},
    {"glVertexAttrib4f", (uintptr_t)&import_226},
    {"glVertexAttribPointer", (uintptr_t)&import_227},
    {"glVertexPointer", (uintptr_t)&import_228},
    {"glViewport", (uintptr_t)&import_229},
    {"gmtime", (uintptr_t)&import_230},
    {"inet_addr", (uintptr_t)&import_231},
    {"inet_ntoa", (uintptr_t)&import_232},
    {"ioctl", (uintptr_t)&import_233},
    {"iswalpha", (uintptr_t)&import_234},
    {"iswcntrl", (uintptr_t)&import_235},
    {"iswdigit", (uintptr_t)&import_236},
    {"iswlower", (uintptr_t)&import_237},
    {"iswprint", (uintptr_t)&import_238},
    {"iswpunct", (uintptr_t)&import_239},
    {"iswspace", (uintptr_t)&import_240},
    {"iswupper", (uintptr_t)&import_241},
    {"iswxdigit", (uintptr_t)&import_242},
    {"ldexpf", (uintptr_t)&import_243},
    {"listen", (uintptr_t)&import_244},
    {"localtime", (uintptr_t)&import_245},
    {"localtime_r", (uintptr_t)&import_246},
    {"log10", (uintptr_t)&import_247},
    {"logf", (uintptr_t)&import_248},
    {"longjmp", (uintptr_t)&import_249},
    {"lrand48", (uintptr_t)&import_250},
    {"lseek", (uintptr_t)&import_251},
    {"malloc", (uintptr_t)&import_252},
    {"memchr", (uintptr_t)&import_253},
    {"memcmp", (uintptr_t)&import_254},
    {"memcpy", (uintptr_t)&import_255},
    {"memmove", (uintptr_t)&import_256},
    {"memset", (uintptr_t)&import_257},
    {"mktime", (uintptr_t)&import_258},
    {"mmap", (uintptr_t)&import_259},
    {"modff", (uintptr_t)&import_260},
    {"munmap", (uintptr_t)&import_261},
    {"nanosleep", (uintptr_t)&import_262},
    {"open", (uintptr_t)&import_263},
    {"pow", (uintptr_t)&import_264},
    {"powf", (uintptr_t)&import_265},
    {"printf", (uintptr_t)&import_266},
    {"pthread_create", (uintptr_t)&import_267},
    {"pthread_exit", (uintptr_t)&import_268},
    {"pthread_getspecific", (uintptr_t)&import_269},
    {"pthread_join", (uintptr_t)&import_270},
    {"pthread_key_create", (uintptr_t)&import_271},
    {"pthread_kill", (uintptr_t)&import_272},
    {"pthread_mutex_destroy", (uintptr_t)&import_273},
    {"pthread_mutex_init", (uintptr_t)&import_274},
    {"pthread_mutex_lock", (uintptr_t)&import_275},
    {"pthread_mutex_trylock", (uintptr_t)&import_276},
    {"pthread_mutex_unlock", (uintptr_t)&import_277},
    {"pthread_self", (uintptr_t)&import_278},
    {"pthread_setspecific", (uintptr_t)&import_279},
    {"putc", (uintptr_t)&import_280},
    {"putchar", (uintptr_t)&import_281},
    {"puts", (uintptr_t)&import_282},
    {"qsort", (uintptr_t)&import_283},
    {"read", (uintptr_t)&import_284},
    {"realloc", (uintptr_t)&import_285},
    {"recv", (uintptr_t)&import_286},
    {"recvfrom", (uintptr_t)&import_287},
    {"remove", (uintptr_t)&import_288},
    {"rename", (uintptr_t)&import_289},
    {"select", (uintptr_t)&import_290},
    {"send", (uintptr_t)&import_291},
    {"sendto", (uintptr_t)&import_292},
    {"setjmp", (uintptr_t)&import_293},
    {"setlocale", (uintptr_t)&import_294},
    {"setsockopt", (uintptr_t)&import_295},
    {"setvbuf", (uintptr_t)&import_296},
    {"sigaction", (uintptr_t)&import_297},
    {"sin", (uintptr_t)&import_298},
    {"sinf", (uintptr_t)&import_299},
    {"sinh", (uintptr_t)&import_300},
    {"snprintf", (uintptr_t)&import_301},
    {"socket", (uintptr_t)&import_302},
    {"sprintf", (uintptr_t)&import_303},
    {"sqrt", (uintptr_t)&import_304},
    {"sqrtf", (uintptr_t)&import_305},
    {"srand48", (uintptr_t)&import_306},
    {"sscanf", (uintptr_t)&import_307},
    {"strcasecmp", (uintptr_t)&import_308},
    {"strcat", (uintptr_t)&import_309},
    {"strchr", (uintptr_t)&import_310},
    {"strcmp", (uintptr_t)&import_311},
    {"strcoll", (uintptr_t)&import_312},
    {"strcpy", (uintptr_t)&import_313},
    {"strcspn", (uintptr_t)&import_314},
    {"strerror", (uintptr_t)&import_315},
    {"strftime", (uintptr_t)&import_316},
    {"strlcpy", (uintptr_t)&import_317},
    {"strlen", (uintptr_t)&import_318},
    {"strncasecmp", (uintptr_t)&import_319},
    {"strncat", (uintptr_t)&import_320},
    {"strncmp", (uintptr_t)&import_321},
    {"strncpy", (uintptr_t)&import_322},
    {"strpbrk", (uintptr_t)&import_323},
    {"strrchr", (uintptr_t)&import_324},
    {"strstr", (uintptr_t)&import_325},
    {"strtod", (uintptr_t)&import_326},
    {"strtok", (uintptr_t)&import_327},
    {"strtol", (uintptr_t)&import_328},
    {"strtoul", (uintptr_t)&import_329},
    {"swprintf", (uintptr_t)&import_330},
    {"sysconf", (uintptr_t)&import_331},
    {"system", (uintptr_t)&import_332},
    {"tan", (uintptr_t)&import_333},
    {"tanf", (uintptr_t)&import_334},
    {"tanh", (uintptr_t)&import_335},
    {"time", (uintptr_t)&import_336},
    {"tmpfile", (uintptr_t)&import_337},
    {"tmpnam", (uintptr_t)&import_338},
    {"towlower", (uintptr_t)&import_339},
    {"towupper", (uintptr_t)&import_340},
    {"ungetc", (uintptr_t)&import_341},
    {"unlink", (uintptr_t)&import_342},
    {"usleep", (uintptr_t)&import_343},
    {"vsnprintf", (uintptr_t)&import_344},
    {"vsprintf", (uintptr_t)&import_345},
    {"wcscmp", (uintptr_t)&import_346},
    {"wcscpy", (uintptr_t)&import_347},
    {"wcslen", (uintptr_t)&import_348},
    {"wcsncpy", (uintptr_t)&import_349},
    {"write", (uintptr_t)&import_350},
};
const int port_imports_size = sizeof(port_imports);
